### ISSUE TITLE
set_current_tenant_through_filter not work with devise 

### ISSUE THREAD

**Issue by fmh** [ErwinM/acts_as_tenant#100]
Hi,
with devise it does not work , because i think the before_filter cause this issue ,
i think adding support for around_filter resolve this issue, 
I use the set_current_tenant_through_filter and a prepend_before_filter callback in my application_controller to log_in and registration, but with logout it does not work. 
Other closed issues : 
#20 #49 #24 

Versions :
Rails 4.2.0
acts_as_tenant 0.3.7
devise 3.4.1

**Comment by ErwinM** [comment]
Can you provide a test application to illustrate the behavior? Then I could have a look.

**Comment by fmh** [comment]
https://github.com/fmh/aat

**Comment by fmh** [comment]
change config.require_tenant to false resolve my issue, 
i try true and raise ActsAsTenant::Errors::NoTenantSet
i look in my log and the last request is :  User Load (0.3ms)  SELECT `users`.* FROM `users`
is devise select * users by default or ignore default_scope ?

**Comment by fmh** [comment]
up
