### ISSUE TITLE
How to remove objects in the console?

### ISSUE THREAD

**Issue by arnekolja** [ErwinM/acts_as_tenant#102]
When using acts_as_tenant and using the rails console, I, naturally, can not any more just

<pre><code>i = MyItem.first
i.destroy</code></pre>

as

<pre><code>tracked owner: Proc.new{ |controller, model| controller.current_user }</code></pre>

does not get a controller passed any more.

Do you have an idea how to work around this? I deleted the items directly in the db this time, but it's not very convenient when developing.

**Comment by ErwinM** [comment]
You can set the current tenant in the console first by doing: `ActsasTenant.current_tenant= sometenant`                                                                                                                                                                                                                                                                          Erwin                                                                                                                                                                                                                From: Arne-Kolja BachsteinSent: Sunday, 1 February 2015 16:51To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantSubject: [acts_as_tenant] How to remove objects in the console? (#102)When using acts_as_tenant I, naturally, can not any more just

i = MyItem.first
i.destroy

as

tracked owner: Proc.new{ |controller, model| controller.current_user }

does not get a controller passed any more.

Do you have an idea how to work around this? I deleted the items directly in the db this time, but it's not very convenient when developing.

—Reply to this email directly or view it on GitHub.

**Comment by arnekolja** [comment]
Thanks, that helped!
