### ISSUE TITLE
Tenant lost during test - request_store related?

### ISSUE THREAD

**Issue by neilsmith** [ErwinM/acts_as_tenant#103]
Since upgrading ActsAsTenant to 0.3.7, I'm finding my integration tests failing - the tenant is set initially, but following a "get" request, the tenant is then nil.

In other words:

```ruby
    ActsAsTenant.current_tenant = test_tenants(:test)
    assert_equal test_tenants(:test), ActsAsTenant.current_tenant # This works
    # at this point, ActsAsTenant.current_tenant is a tenant

    get '/' # This does set the tenant
    assert_equal test_tenants(:test), ActsAsTenant.current_tenant # This fails
    # at this point, ActsAsTenant.current_tenant is nil
```

After some trial and error, I think I've found the issue is related to the request_store gem - as acts_as_tenant has a dependency on this, Bundler updates request_store when I update acts_as_tenant.

If I use acts_as_tenant 0.3.7 with request_store 1.0.5, the above code works. As soon as I upgrade request_store to 1.0.6 or newer (such as the current 1.1.0), the code fails.

I've put together a very simple test application to demonstrate this:
https://github.com/neilsmith/acts-as-tenant-test-application

By default, the Gemfile specifies 1.0.6 and the test fails, but if you drop back to 1.0.5 you should (hopefully!) see the test working again.

I'm running these tests on Ruby 2.2.0.

Any thoughts or comments would be appreciated - I'm not really sure if this is an ActsAsTenant issue, or a RequestStore issue, or whether I'm just misunderstanding something completely.

**Comment by neilsmith** [comment]
Aha, I think I've found the culprit - this code:
https://github.com/steveklabnik/request_store/blob/master/lib/request_store/middleware.rb

If I read this correctly, this clears the RequestStore after each request - would would explain why, after the request has completed, we're no longer available to see what tenant is set.

Perhaps, upon reflection, the original behaviour was not intentional, and it's just unfortunate I had some tests that replied upon them?

**Comment by ErwinM** [comment]
Your write-up has me a bit puzzled.

The `current_tenant` should definitely NOT survive between requests. It should be set anew with every request. I tested one of our apps with `request_store` 1.1.0 and it works fine.

That said, and I am not familiar with unit:test, but i can't see why your test application is failing to set the tenant. Seems like you are setting it, so a get request should set it..

**Comment by neilsmith** [comment]
Thanks for your reply. It took me a while to see what was going on here, but I think I can simplify it as follows:

This integration test, with acts_as_tenant 1.3.7 and request_store 1.0.5, would work:

```ruby
get '/' # This sets the tenant to test_tenants(:test)
assert_equal test_tenants(:test), ActsAsTenant.current_tenant
```

However, with request_store 1.0.6+, it doesn't any more - because ActsAsTenant.current_tenant is now set to nil when the get request is completed.

Having thought about this, I think the "new" behaviour here is probably correct - the integration test shouldn't be able to "see" what acts_as_tenant was doing inside the request it made.

I'll therefore close this ticket, but thanks for your time and for acts_as_tenant!
