### ISSUE TITLE
current_tenant is nil when subdomain has different case

### ISSUE THREAD

**Issue by a3ammar** [ErwinM/acts_as_tenant#107]
Browser usually normalize host URL, and when a user signs up with a capitalized subdomain `set_current_tenant_by_subdomain` will not find the subdomain.

I could easily solve it by a `before_save` callback, but shouldn't this be part of the gem?

**Comment by ErwinM** [comment]
I fully agree. I would love a PR implementing that.

**Comment by a3ammar** [comment]
I changed `find_tenant_by_subdomain` to use the SQL function `LOWER()` and `.downcase` `request.subdomain` but I can't get the tests to work. Have any tips?

**Comment by ErwinM** [comment]
Could you share your code?

**Comment by a3ammar** [comment]
Certainly, https://github.com/ErwinM/acts_as_tenant/compare/master...a3ammar:master
I can't get a test like this one to work:
```ruby
it "Finds the correct tenant with a mixed case subdomain" do
  @request.host = "ACCOUNT1.example.com"
  expect(Account).to receive(:where).with({subdomain: 'account1'}) {['account1']}
  get :index
  expect(ActsAsTenant.current_tenant).to eq 'account1'
end
```

**Comment by ErwinM** [comment]
@a3ammar I updated `master` with code that makes the lookup case insensitive. I did not use `lower()` on the dbase. I find the app should be responsible for down casing the tenant subdomain at creation.

As a FYI, the correct syntax for your test code would have been:

`expect(Account).to receive(:where).with(lower(subdomain) = ?", "account1") {['account1']}"`

**Comment by a3ammar** [comment]
Thanks! Keep up the good work.
