### ISSUE TITLE
extension proposal

### ISSUE THREAD

**Issue by doofpot** [ErwinM/acts_as_tenant#108]
In ActAsTenant.configure, the only option you can set is require_tenant

I would propose to extend it with
config.notenantset_redirect = <some route>

If it can be extended with a warning/notice/error it would be more nice; i think it's not more than adding an check to error.rb.

**Comment by doofpot** [comment]
Ok, by accident I found a simple solution for this in the cancancan gem

class ApplicationController < ActionController::Base
...
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  rescue_from ActsAsTenant::Errors::NoTenantSet do |exception|
    redirect_to root_url, :alert => exception.message
  end

The first is from the cancancan gem; the second one works for act_as_a_tenant

**Comment by ErwinM** [comment]
I think that is an elegant way to force the redirect. Glad you got it to work.                                                                                                                                                                                                                                                                                                                                         Erwin                                                                                                                                                                                                                From: A. SchippersSent: Wednesday, 29 April 2015 16:39To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantSubject: Re: [acts_as_tenant] extension proposal (#108)Ok, by accident I found a simple solution for this in the cancancan gem

class ApplicationController < ActionController::Base
...
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

rescue_from ActsAsTenant::Errors::NoTenantSet do |exception|
    redirect_to root_url, :alert => exception.message
  end

The first is from the cancancan gem; the second one works for act_as_a_tenant

—Reply to this email directly or view it on GitHub.
