### ISSUE TITLE
0.3.8 release

### ISSUE THREAD

**Issue by vronin-okta** [ErwinM/acts_as_tenant#109]
Hi,

Can you please create b 0.3.8 and publish new vesion to RubyGem when you will have time

Regards,
Victor

**Comment by ErwinM** [comment]
Np. I'll have access to my development environment tomorrow and push it.                                                                                                                                                                                                                                                                                                                                         Erwin                                                                                                                                                                                                                From: vronin-oktaSent: Friday, 8 May 2015 00:18To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantSubject: [acts_as_tenant] 0.3.8 release (#109)Hi,

Can you please create b 0.3.8 and publish new vesion to RubyGem when you will have time

Regards,
Victor

—Reply to this email directly or view it on GitHub.

**Comment by ErwinM** [comment]
v0.3.8 has now been pushed to Rubygems.
