### ISSUE TITLE
Model find first does not work when tenant not set

### ISSUE THREAD

**Issue by balen** [ErwinM/acts_as_tenant#111]
This is only a problem in 0.3.8 of act_as_tenant. The issue is with the following, I have a model called SiteConfig. If there is no tenant set I want to just get the first one in the DB to get started:

```
SiteConfig.first
```

returns an array i.e. the "limit 1" is removed from the generated SQL by act_as_tenant. This used to work in 0.3.7.
It appears to be caused by the commit "Always return a criteria for default scope".

**Comment by ErwinM** [comment]
@iangreenleaf This error appears because a fix that was made to ensure mongoid compatibility. I am not familiar enough with mongoid to fix this issue without breaking it for mongoid... Could you have a look?
