### ISSUE TITLE
setting tenant in controller fails traceroute

### ISSUE THREAD

**Issue by MehdiK** [ErwinM/acts_as_tenant#118]
Setting tenant in controller as advised [here](https://github.com/ErwinM/acts_as_tenant#setting-the-current-tenant-in-a-controller-manually) adds a public `set_current_tenant` method to the `ApplicationController` (and all its subclasses by extension) which causes traceroute to fail.

Is it possible to get `set_current_tenant_through_filter` to add the required methods into private space (as opposed to public methods)?

P.S. Thanks for the awesome gem!

**Comment by ErwinM** [comment]
That sounds sensible. Could you provide a PR?
