### ISSUE TITLE
Can a model belong to more than one tenant?

### ISSUE THREAD

**Issue by hayesmp** [ErwinM/acts_as_tenant#121]
We have a use case where users need to belong to more than one tenant. Is this possible with this gem?

**Comment by bweave** [comment]
Would love to know the answer to this as well.

**Comment by ErwinM** [comment]
It does not support that use case out of the box. AaT looks for a single column in each scoped model to retrieve the tenant. If a model (`user` in your case) would have to belong to multiple tenants that would have to be handled in a different way..
