### ISSUE TITLE
Act_as_tenant not working on production environment in rails4

### ISSUE THREAD

**Issue by somiryu** [ErwinM/acts_as_tenant#127]
After migrating an app from rails 3 to rails 4, we're receiving this error when trying to load the app in production:

.../.rvm/gems/ruby-2.1.1/gems/activerecord-4.2.2/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `act_as_tenant' for #<Class:0x00000109d795b0> (NoMethodError)

It works in development but it crashes if I start the server with -e production.

I would appreciate the help!

**Comment by ErwinM** [comment]
The error suggests the acts_as_tenant gem is not loaded...                                                                                                                                                                                                                                                                                                                                        Erwin                                                                                                                                                                                                                From: somiryuSent: Monday, 4 January 2016 19:11To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantSubject: [acts_as_tenant] Act_as_tenant not working on production environment in rails4 (#127)After migrating an app from rails 3 to rails 4, we're receiving this error when trying to load the app in production:

/rvm/gems/ruby-211/gems/activerecord-422/lib/active_record/dynamic_matchersrb:26:in method_missing': undefined methodact_as_tenant' for #Class:0x00000109d795b0 (NoMethodError)

It works in development but it crashes if I start the server with -e production

I would appreciate the help!

—Reply to this email directly or view it on GitHub.
