### ISSUE TITLE
Backup and Restore a single tenant

### ISSUE THREAD

**Issue by burtondav** [ErwinM/acts_as_tenant#128]
I'm using acts_as_tenant in a Rails app.
The database is PG.

Is there a way to backup and restore a single tenant?

**Comment by ErwinM** [comment]
What do you want to do exactly? A tenant is nothing more than a scope on your DB. You could restore with that scope aswell.                                                                                                                                                                                                                                                                                                                                         Erwin                                                                                                                                                                                                                From: David BurtonSent: Friday, 22 January 2016 17:47To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantSubject: [acts_as_tenant] Backup and Restore a single tenant (#128)I'm using acts_as_tenant in a Rails app.
The database is PG.

Is there a way to backup and restore a single tenant?

—Reply to this email directly or view it on GitHub.

**Comment by burtondav** [comment]
I'm using acts_as_tenant to allow multiple customers (of ours) to use the same application/server on Heroku.  It works great - thanks!

But, I'm not experienced enough with PG to backup and restore a single tenant.  Could I use pgAdmin3 to do that? Or Navicat?  

Perhaps this is the wrong place to ask this question.  If it is - please let me know.

Thanks - Dave

**Comment by lenart** [comment]
@burtondav If I understand you correctly you want to backup single tenant's data. To do so you don't have to worry about acts_as_tenant at all - it's not really related. You can backup the data by using tools like `pg_dump`, pgAdmin3, Navicat or similar ... the only thing that you'll need to figure out is how to apply tenant scope - to only dump/backup records belonging to a single tenant.

**Comment by burtondav** [comment]
Thanks
