### ISSUE TITLE
set_current_tenant_by_subdomain doesn't work for 2-level TLDs

### ISSUE THREAD

**Issue by brigneld** [ErwinM/acts_as_tenant#139]
`set_current_tenant_by_subdomain` on `subd.example.com.au` returns `example`, rather than `subd`. This seems to be associated with:
`ActsAsTenant.current_tenant = tenant_class.where(tenant_column => request.subdomains.last).first`
in controller_extensions.rb, line 21.

Should this line actually be:
`ActsAsTenant.current_tenant = tenant_class.where(tenant_column => request.subdomains.first).first` ?

Note that this would affect .co.uk domains and some other domains where TLD is a country code (ccTLD).

**Comment by bucksw** [comment]
You need to set current_tenant via the second step that is outlined not the first.  It says in the documentation that set_current_tenant_by_subdomain doesn't work in all cases such as multiple domains like this.  In my Application Controller I just did this and works fine if you have multiple subdomains or even 1.  It's great if you have staging environment that is staging.domain.com but production is domain.com.... 
`set_current_tenant_through_filter
before_action :set_organization

def set_organization
    @organization = Organization.where(subdomain: request.subdomains[0]).first
     set_current_tenant(@organization)
end`

**Comment by ErwinM** [comment]
Although making the changes you suggest would work in your case, they are bound to break something for someone else. the `set_current_tenant_by_subdomain` option was meant for the easy case where it would work out of the box. 

Like explained above, for all other cases the customising the filter is the intended way to go.
