### ISSUE TITLE
undefined method `without_tenant' for ActsAsTenant:Module

### ISSUE THREAD

**Issue by crewnet** [ErwinM/acts_as_tenant#140]
When I try to call 
`ActsAsTenant.without_tenant do`
from the controller I get 
`undefined method 'without_tenant' for ActsAsTenant:Module`

Is this a bug, or do I call it wrong?

**Comment by Patsy-issa** [comment]
The functionality has been added to master but a new version has not been released, you will have to link to the repo from your gemfile in order to use it.
`gem 'acts_as_tenant', git: 'https://github.com/ErwinM/acts_as_tenant', ref: '960d3df'`

**Comment by burtondav** [comment]
I'm getting the same error. My gemlock is:
    acts_as_tenant (0.3.6)
      rails (>= 3.1)
      request_store (>= 1.0.5)

How do I get the fix?

**Comment by ErwinM** [comment]
I've just pushed the master to ruby gems as version 0.4.1.

If you update the gem your all set to go.

**Comment by burtondav** [comment]
Thank you!
