### ISSUE TITLE
Crash when accessed through the IP

### ISSUE THREAD

**Issue by besi** [ErwinM/acts_as_tenant#151]
In my controller I have the standard call like so:

``` ruby
set_current_tenant_by_subdomain_or_domain( :merchant, :slug, :domain )
```
### Actual result

This results in the following crash, when I access my app via the IP address:

``` crash
NoMethodError (undefined method `downcase' for nil:NilClass):
  acts_as_tenant (0.4.0) lib/acts_as_tenant/controller_extensions.rb:53:in `find_tenant_by_subdomain_or_domain'
```
### Expected result

Since no domain is available, I would expect the `current_tenant` to be `nil`.
### Workaround

I did the following to avoid the crash:

``` ruby
  before_filter -> {
    # Prevent direct access to the ip
    redirect_to '//mydomain.com' if request.domain.blank?
  }

  set_current_tenant_by_subdomain_or_domain( :merchant, :slug, :domain )
```

<sub>Internal Issue `VS#213`</sub>

**Comment by daya** [comment]
@besi have you considered submitting a pull request for this? seems like this oughta be in the core

**Comment by ErwinM** [comment]
I think that workaround is fine. It would be hard to implement this in AaT since it requires the explicit domain of the app. Which you could pass in an option or something, but then again the workaround is quite simple.

**Comment by besi** [comment]
@ErwinM I would suggest however, that the the current tenant is simply `nil`, if the domain is not set. In my case I got a crash. I think this case should be prevented.
