### ISSUE TITLE
Blog reference doesn't exist

### ISSUE THREAD

**Issue by AugustoPedraza** [ErwinM/acts_as_tenant#152]
Does not the http://www.rollcallapp.com/blog exist anymore?

**Comment by ErwinM** [comment]
It might be down since that project got put on ice. I'll see if I can include the post in the github repo. 
Will be in a little over a week or so as I am currently traveling. 

Erwin

		_____________________________

**Comment by jekuno** [comment]
Does "put on ice" mean that you might abandon the project?
It seems as if the `milia` gem also doesn't get developed actively any longer ("retired from software development": https://github.com/dsaronin/milia/issues/64#issuecomment-193925511).

If so this would mean that the two most popular row based multi tenanting gems might vanish.
Are there any good alternatives besides the schema based `apartment` gem https://github.com/influitive/apartment?

**Comment by undergroundwebdesigns** [comment]
I'm currently evaluating options to help enforce multi-tenant data protection in our app (which up to now has been rather ad-hoc about it) and it looks like it comes down to `acts_as_tenant` or `milia`. So far I much prefer `acts_as_tenant`'s interface as we're running an API app and aren't really using Devise, which `milia` seems especially tied to. 

@ErwinM any feedback on whether this gem will continue to be maintained? If not, would you be open to the possibility of additional maintainers and/or passing it off to someone else? It looks like there's a substantial community already using it and providing PR's, I'd be happy to help manage getting some of those merged in & the open issues cleaned up.
