### ISSUE TITLE
Is it possible to exclude some records from the acts_as_tenant scoping?

### ISSUE THREAD

**Issue by Greyoxide** [ErwinM/acts_as_tenant#153]
I have a model(AddressType) which will mostly contain tenant data.  However, I also need to be able to set some records as defaults.  These default records would be available to all subscribers in addition to the records they created.

So for example:

`@address_types = AddressType.all`

would pull both tenant created address_types as well as the default records.  Additionally I would need to be able to call:

`address.address_type.description`

And have it work for both tenant created records as well as default records.

Is this possible with acts_as_tenant?

**Comment by toobulkeh** [comment]
Sounds like a case for STI with acts_as_tenant only on one of the inherited models.
