### ISSUE TITLE
Can't use the gem with an ApplicationController extending ActionController::API

### ISSUE THREAD

**Issue by kbogtob** [ErwinM/acts_as_tenant#156]
Hi pals, I'm using the gem on an _API only_ rails app and I'm having issues out of the box. 

As my ApplicationController is extending ActionController::API instead of ActionController::Base : 
* the ApplicationController doesn't extend the Controller Extensions
* the ApplicationController doesn't have a #helper_method method

I'll make a PR to fix those problems but I need your opinion on a point : Do you prefer me implementing another ControllerExtensions module for ActionController::API or a conditional call to #helper_method in the current ControllerExtensions?

Cheers!

**Comment by ErwinM** [comment]
I think the solution in your PR is fine. A separate ControllerExtension might be a bit excessive if we are only putting in 2 conditionals..thx for the PR

**Comment by kbogtob** [comment]
You're welcome, thank you for this gem!

**Comment by Youssefares** [comment]
a new release for this?
