### ISSUE TITLE
Adding Index will effect performance ?

### ISSUE THREAD

**Issue by wonderer007** [ErwinM/acts_as_tenant#158]
Hello

I am using act_as_tenant for my application but I have one reservation, normally we add index **when we need to efficiently retrieve a relatively small number of rows from a table** while in case of multi tenant application (which is my case as well) we are having tenant_id in almost each table where some of the table might grow to millions of records per tenant. Apart from index on tenant_id I have index on deleted_at columns in every table for soft delete gem **paranoia**. I am sensing that with passage of time insertion time will increase for those tables and that will effect whole system.  
How can we address this issue ?

Thanks

**Comment by ErwinM** [comment]
We include `tenant_id` as an additional index on any model that is scoped to a tenant. Additional, where it makes sense we add `tenant_id` as an additional index. For example, our 'recents' table, which holds millions of records, is indexed on ['tenant_id', 'user_id'].
