### ISSUE TITLE
prevent certain sub-domains from created by the user?

### ISSUE THREAD

**Issue by mzaragoza** [ErwinM/acts_as_tenant#159]
is it posible to prevent certain sub-domains from created by the user?

Thanks

**Comment by vfonic** [comment]
I think this is not the scope of this gem. You should prevent creation of those subdomains yourself in some other part of your application.

**Comment by ErwinM** [comment]
@vfonic is right. The gem only enforces scoping of models to the tenant. It does not handle creation of subdomains. Creation (and restriction) is up to the developer of the app.
