### ISSUE TITLE
before_filter is deprecated in Rails 5.1 - set_current_tenant_by_subdomain uses it

### ISSUE THREAD

**Issue by offerquant** [ErwinM/acts_as_tenant#160]
set_current_tenant_by_subdomain uses before_filter, but it's been deprecated in Rails 5.1

DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <class:ApplicationController>

**Comment by plicjo** [comment]
This is fixed on master.

**Comment by plicjo** [comment]
@ErwinM I'm not sure what's going on, but master is showing `before_filter` https://github.com/ErwinM/acts_as_tenant/blob/master/lib/acts_as_tenant/controller_extensions.rb#L17

But your last change to that line changed it to a before_action? That's pretty confusing.

**Comment by wakproductions** [comment]
Looks like he changed some of the comments but forgot to change the actual code. The front page says build passing but Travis is looking at the most recent pull request ⚠️ , which should be merged: https://github.com/ErwinM/acts_as_tenant/pull/165

**Comment by Techbrunch** [comment]
@ErwinM Not sure what happened with the latest releases but Github does'nt have any tags for 0.4.0 and 0.4.1 and releases for them. We ran into the issue fixed by 4f73051e8e3ef but this doesn't appear to be in 0.4.1

**Comment by ErwinM** [comment]
I don't know what happened here. I released a new version (0.4.2) which is synced up with the master branch here...

**Comment by plicjo** [comment]
Thanks @ErwinM !!
