### ISSUE TITLE
Separate logs for each tenant

### ISSUE THREAD

**Issue by wonderer007** [ErwinM/acts_as_tenant#163]
I am using act_as_tenant for a multi-tenant app. The issue we are having is log of all the tenant is shared i.e. one log file for every tenant. Is it possible either of 2 options to have

1. Different log file for each tenant
2. Different text colour in log file for each tenant

I am not looking for pre build solution if there isn't any please guide me how should I approach it I will build it myself. Thanks

**Comment by wonderer007** [comment]
@toobulkeh link is broken [Papertrail App](https://github.com/ErwinM/acts_as_tenant/issues/Papertrailapp.com)

**Comment by toobulkeh** [comment]
Fixed.
