### ISSUE TITLE
Getting "Model association is invalid [ActsAsTenant]" Error When Creating A New Record

### ISSUE THREAD

**Issue by muaad** [ErwinM/acts_as_tenant#168]
Let's say I have two models: `House` and `Room`. `Room` belongs to `House`. When creating a new `Room` record, if I skip setting the `house_id` for it, I get `House association is invalid [ActsAsTenant]`. Is there a way I can create new `Room` records without having to set `house_id`.  There are some scenarios in which I don't want to set it.

Thanks.

**Comment by ErwinM** [comment]
I'm not entirely sure off-hand, but if you set the tenant_id to `0` it should be accepted and that record will be visible to all tenants..I think
