### ISSUE TITLE
Change the way how subdomains are handled

### ISSUE THREAD

**Issue by tmaier** [ErwinM/acts_as_tenant#172]
acts_as_tenant supports since version 0.3.2 (commit 0ee45147484534fb5c7ce36c9e4c012861cfc162) subdomains like the following:

- `subdomain.example.com`
- `www.subdomain.example.com`

the relevant method is: [see code](https://github.com/ErwinM/acts_as_tenant/blob/bf9e4b93d775807f85ac342b2aa6a290ffbd0d1b/lib/acts_as_tenant/controller_extensions.rb#L22-L26)
```ruby
          def find_tenant_by_subdomain
            if request.subdomains.last
              ActsAsTenant.current_tenant = tenant_class.where(tenant_column => request.subdomains.last.downcase).first
            end
          end
```

Supporting `www.subdomain.example.com` is not that useful from todays perspective
* SSL certificates are not being issued for `www.*.example.com`. I assume SSL to be enabled with any relevant application nowadays
* Current implementation does not support domains, like `co.uk` (UK) (see #139)
* Limits flexibility of how many subdomains can be used. Relevant for test deployments (e.g. with GitLab Review App feature, where the domain could be `<my-subdomain>.<my branch>.<my project>.<my-domain>`)

I understand that the current behaviour is there since 2014 and cannot be simply changed.

I would like to propose two options:
1. Add a new parameter to `set_current_tenant_by_subdomain` which is `subdomain_index`. Allowed values would be `:first` or `:last`, `:last` would stay the default.
2. Change the behaviour to `first`, but handle the edge case `www.subdomain` (note the `www`) specifically
3. Add a `set_current_tenant_by_first_subdomain` method (see Pull Request #173)

I also think we should give the recommendation to implement somewhere a redirect from `www.subdomain.example.com` to `subdomain.example.com`

What do you think?

**Comment by ErwinM** [comment]
I agree that handling the `www.subdomain` case is not that useful. I also agree that for legacy reasons we should keep supporting the 'www'-case as to not break things.

I am not too enthusiastic about adding a bunch of methods to cover different use cases. Programmers are more than capable of defining their own filter through the `set_current_tenant_through_filter`-method, which allows them to parse the URL any way they would like.

I like the idea of your suggestion (1). Why do you feel we also need (3) ?

**Comment by tmaier** [comment]
I simply thought that 3 is simpler, but I have no hard feelings on any

**Comment by ErwinM** [comment]
I'd propose we either add the suggested parameter to the existing method (your 1), or go for two methods (first and last). Not both. 

All in all I think I favor the first option. What do you think?
