### ISSUE TITLE
Rails 5.2 - Global records - ActiveRecord::RecordInvalid (Validation failed: Account must exist, Account must exist)

### ISSUE THREAD

**Issue by stormywrench** [ErwinM/acts_as_tenant#179]
Thank you Erwin and contributors for this gem.

I've been trying out global records feature in Rails 5.2 but it seems to have some bug when creating global records.

Model is defined like this:

class Certificate < ApplicationRecord
  acts_as_tenant :account, has_global_records: true

  belongs_to :account
end

Then, from Rails console:

(some checks first)

irb(main):001:0> ActsAsTenant.models_with_global_records
=> [Certificate (call 'Certificate.connection' to establish a connection)]
irb(main):002:0> ActsAsTenant.tenant_klass
=> :account

(now the test)

irb(main):004:0> ActsAsTenant.current_tenant
=> nil
irb(main):005:0> Certificate.create!
   (0.3ms)  BEGIN
   (0.3ms)  ROLLBACK
Traceback (most recent call last):
        1: from (irb):5
ActiveRecord::RecordInvalid (Validation failed: Account must exist, Account must exist)

I was expecting to have the record created with account_id set to nil. Then, this global record should be returned with and without tenant set.

This is similar to the spec test included with the gem:

  describe 'A tenant model with global records' do
    before do
      @account = Account.create!(:name => 'foo')
      @project1 = GlobalProject.create!(:name => 'foobar global')
      @project2 = GlobalProject.create!(:name => 'unaccessible project', :account => Account.create!)
      ActsAsTenant.current_tenant = @account
      @project3 = GlobalProject.create!(:name => 'foobar')
    end

    it 'should return two projects' do
      expect(GlobalProject.all.count).to eq(2)
    end
end

I noticed that the spec model class inherited from ActiveRecord::Base instead of ApplicationRecord (Rails 5.2):

class GlobalProject < ActiveRecord::Base
  self.table_name = 'projects'

  acts_as_tenant :account, has_global_records: true
  validates_uniqueness_to_tenant :name
end

Maybe that is the cause of the issue.

Thank you for having a look and give some comments.

Best regards.
Gonzalo.

**Comment by ryanicle** [comment]
@stormywrench Have you found a solution for this?

This works for me. Created exact another model without this line.

`acts_as_tenant(:account)`

**Comment by pruzicka** [comment]
@stormywrench - did you find working solution? Thank you
