### ISSUE TITLE
Do I really need foreign_keys on my "tenanted" tables?

### ISSUE THREAD

**Issue by ghost** [ErwinM/acts_as_tenant#180]
Do I really need foreign_keys on my "tenanted" tables?

I'm creating tables like this (Rails 5.2):

```ruby
class AddTeamToPlayers < ActiveRecord::Migration[5.2]
  def change
    add_reference :players, :team, foreign_key: true
  end
end
```

Do I really need this part:

`, foreign_key: true` ???

Maybe not, isn't it?

**Comment by tmaier** [comment]
working with foreign keys increases data integrity.

This means `foreign_key: true` is not a MUST, but it SHOULD be used.

**Comment by ErwinM** [comment]
what @tmaier said..
