### ISSUE TITLE
Acts_as_tenant and devise. Do I really need tenant on users table?

### ISSUE THREAD

**Issue by ghost** [ErwinM/acts_as_tenant#181]
I'm trying https://github.com/ErwinM/acts_as_tenant gem for my Rails 5.2.

I'm also using `devise`.

If I add `acts_as_tenant(:team)` to my `User` model it doesn't work because of this: https://github.com/ErwinM/acts_as_tenant/issues/49.

But I was wondering if I really need tenant in `users` table.

Do I?

Maybe just for the administration logic?

And what if my administration logic is not in the same app?

Maybe just a `has_many :users` and `belongs_to :team` is enough. Am I wrong?

**Comment by ErwinM** [comment]
you don't *need* it of course. You could make sure `teams` don't see each other's users yourself. Of course, that is exactly the use case `acts_as_tenant` was designed to tackle for you..
