### ISSUE TITLE
without_tenant doesn't work if default_tenant is set

### ISSUE THREAD

**Issue by maslenkov** [ErwinM/acts_as_tenant#187]
### The problem is:
In tests I've set default_tenant as it is suggested in [README](https://github.com/ErwinM/acts_as_tenant#testing)
Then I run test like that:
```ruby
    it 'works correct with multitenancy' do
      BinCount.create! # so it is created with default_tenant
      ActsAsTenant.with_tenant(Account.create(name: 'second')) { BinCount.create! }
      ActsAsTenant.without_tenant do
        expect(BinCount.count).to eql 2 # but it is 1
      end
    end
```
**I've added the test in PR** #186

---
### about possible implementations
I think the problem can happen because https://github.com/ErwinM/acts_as_tenant/blob/master/lib/acts_as_tenant/model_extensions.rb#L34 doesn't check for the `unscoped` flag. But if I set it somehow like:
```ruby
  def self.current_tenant
    RequestStore.store[:current_tenant] || (!self.unscoped && self.default_tenant)
  end
```
Then some other specs fail.

**Comment by ErwinM** [comment]
@maslenkov good catch. I fixed the issue in the master branch. Let me know if this also works in your case.

**Comment by maslenkov** [comment]
@ErwinM thank you for your great job! Your fix works great! I've just pushed a tiny code style improvements for your comment (PR #189). Feel free to close it if you think that this is unnecessary. 

And thank you one more time!
