### ISSUE TITLE
0.4.3?

### ISSUE THREAD

**Issue by dpaola2** [ErwinM/acts_as_tenant#193]
I just installed this gem into a new project and notice that it's version 0.4.3 (which doesn't appear as a release or a tag here).  Additionally in my rails 5.2.1 project it doesn't seem to set the tenant correctly. `ActsAsTenant.set_current_tenant` seems to succeed but then calling `ActsAsTenant.current_tenant` returns `nil` every time.

Thanks for publishing this gem -- it seems  a lot simpler and geared towards my use case than something like https://github.com/influitive/apartment but unfortunately I can't seem to get it to work.

**Comment by jaydorsey** [comment]
Can you post the actual code you're using to set the tenant (and the pre-cursor code--how are you looking the tenant up?). It could be something as simple as an invalid record/tenant (e.g. calling `Foo.create` and failing silently) but it's hard to tell (for me at least) without a longer code snipet.

0.4.3 is the latest published version per [rubygems](https://rubygems.org/gems/acts_as_tenant). It looks like the tag was missed in github, but the corresponding [commit](https://github.com/ErwinM/acts_as_tenant/commit/1549965bee146ad725bc6ac196f48653ff2d1d5a) for 0.4.3 is there

**Comment by dpaola2** [comment]
It works for me now, although I can't quite remember what I had to do. I think I downgraded to 0.4.2 and it worked.

I seem to recall there was some confusing sequencing happening - for example, if I set a debug point in a controller action, it didn't seem to set the tenant correctly (even though controller code seemed to have it set). ¯\_(ツ)_/¯

**Comment by excid3** [comment]
Gonna close this and we can reopen if someone can replicate it. 👍
