### ISSUE TITLE
added Presence Validator when model contain acts_as_tenant(:tenant) 

### ISSUE THREAD

**Issue by pvin** [ErwinM/acts_as_tenant#196]
rails 5.2.1  ruby 2.5.1

My Model 

class InputForm < ApplicationRecord
   acts_as_tenant(:tenant)
end

**InputForm.validators** shows

#<ActiveRecord::Validations::PresenceValidator:0x000000000baaae28
  @attributes=[:tenant],
  @options={:message=>:required}>

**This is not allowing me to create the InputForm without tenant.**

Note : I don't have any  config setup (config.require_tenant = true ) or file  like config/initializers/acts_as_tenant.rb

Also tried creating the a file and  s**etting config.require_tenant = false**
making no difference

What i'm doing wrong ?

**Comment by sai92messy** [comment]
Have you tried the `optional: true` options when specifying acts_as_tenant?
```
class InputForm < ApplicationRecord
  acts_as_tenant :tenant, optional: true
end
```

**Comment by pvin** [comment]
@sai92messy Great Man!! Thanks for pointing the config/application.rb 
`config.active_record.belongs_to_required_by_default = false`
which is the reason for the validation error.  Closing the issue.
