### ISSUE TITLE
Using set_current_tenant_through_filter with Devise destroys user sessions

### ISSUE THREAD

**Issue by BenStW** [ErwinM/acts_as_tenant#20]
When I use Devise and your gem with setting manually the current tenant in the controller, 
then sessions of users of other tenants are destroyed when an user of a different tenant logs in.
I reproduced it a blank application. That's my ApplicationController:

class ApplicationController < ActionController::Base
  protect_from_forgery
  set_current_tenant_through_filter
  before_filter :find_the_current_tenant
  before_filter :authenticate_user!

  def find_the_current_tenant
    if current_user
      set_current_tenant(current_user.tenant)
    else
      set_current_tenant(nil)
    end

  end  
end

**Comment by fmh** [comment]
the same in #100
