### ISSUE TITLE
The link in the GitHub description is broken (HTTP 404)

### ISSUE THREAD

**Issue by Coeur** [ErwinM/acts_as_tenant#205]
Go to the repository page: https://github.com/ErwinM/acts_as_tenant
Check the description on top, it reads:
>Easy multi-tenancy for Rails in a shared database setup http://www.rollcallapp.com/blog

But that link is broken.

**Comment by ErwinM** [comment]
Thx. I've removed the link. The blog post is linked correctly in the README.
