### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by niborg** [ErwinM/acts_as_tenant#206]
There are numerous issues and PRs that have been lingering without feedback. As far as I can tell, the gem is still actively used in the community. Additional maintainers should be easy to find if the README invited them.

Alternatively, @alexdeschamps would devs at your company be willing to maintain the repo from its fork [here](https://github.com/clio/acts_as_tenant)?

**Comment by ErwinM** [comment]
I do not work with RoR much myself anymore, so I only check this Repo a couple times a year.

That said, if people want to help maintain it, they'd be more than welcome!

**Comment by aert** [comment]
Just found this, in case it's of interest to anyone : https://github.com/citusdata/activerecord-multi-tenant
Seems to be based on this repo.

**Comment by sanchez2210** [comment]
> I do not work with RoR much myself anymore, so I only check this Repo a couple times a year.
> 
> That said, if people want to help maintain it, they'd be more than welcome!
> 
> I'll add an invitation to do so t the readme (good idea!)

https://github.com/ErwinM/acts_as_tenant/issues/234 :)
