### ISSUE TITLE
Form Validation Error: Billing address association is invalid [ActsAsTenant] for #<Order:0x00007fa57c0f1058>

### ISSUE THREAD

**Issue by cavebring** [ErwinM/acts_as_tenant#208]
Hi,
I have  a huge project with hundreds of models nested in all different ways. Now I added this fantastic gem to add a top layer of multi tenancy. However I get this error on two of my models and I can not understand why. I have tried to look in the source code as well as trying to set the relationships different.

Is there any specific reason for when this error "association is invalid [ActsAsTenant]"  triggers? What is the most common reason for this error?

**Comment by cavebring** [comment]
My issue is solved. It was because the gem is requiring that a relation exists before saving. So if a related object is deleted but the reference is still on the acting model (in my case here "Order") it will refuse to save before you delete that missing relation, in my case order.address = nil.

**Comment by ErwinM** [comment]
Good to hear you solved your issue. And thx for reporting back.

Groet,
Erwin

________________________________
