### ISSUE TITLE
active_record_primary_key causes failures when initialized early

### ISSUE THREAD

**Issue by chevinbrown** [ErwinM/acts_as_tenant#211]
It appears [this change](https://github.com/ErwinM/acts_as_tenant/commit/6014ca8#diff-fd90cacfeff33c57525685ce430baf4aR199) caused some regressions for us b/c our models get initialized before the db is connected...

It appears to be completely unused also?

I'm still a little fuzzy on the details and can't recreate in the dummy app yet, but want to consult the author before digging in too deep.

**Comment by ErwinM** [comment]
Not sure why that came in...It's gone now in master.
