### ISSUE TITLE
AaT not working with Devise properly

### ISSUE THREAD

**Issue by senorlocksmith** [ErwinM/acts_as_tenant#214]
I hope anyone can provide some advice. I have been building a new rails app with Devise and Acts as Tenant trying to get it setup where if I register I create a user and a tenant. Additionally being able to invite users to be apart of my tenant. Keeping in mind the data stays separate between tenants, but I cannot figure this out. I have followed some of the guides and stumbled around. I even tried Milia and adapting what they did, but its not working on the newer Rails. Id like to be on Rails 6 if possible. Please let me know if you have any suggestions. I have been able to build separate apps getting tenants working on one and getting users working on another. Maybe someone has an idea how to get this accomplished because I have seen a few comments in the issues. Thanks in advance for any help.

**Comment by tsmith-dev** [comment]
Any progress on this? I'm having similar difficulties.

**Comment by mbjornson** [comment]
[https://www.youtube.com/watch?v=dWOzQ0DZBJg](url)

**Comment by aviisekh** [comment]
I am facing the problem with the devise and AaT. My problem is I want to identify the user to be unique in the scope of its tenant. But when I use the devise code inside my user's model the uniqueness is checked across all the tenants, and not in the specific tenant. I see some weird query going on. Below are the query snippets. 
1. When devise is enabled in the model. 
```ruby
User.new(name: 'Test', email: 'aviisekh@gmail.com', tenant_id: 115, phone: "+19843288951").valid?
```
produces following three queries with result false
```sql
User Exists (1.4ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "aviisekh@gmail.com"], ["LIMIT", 1]]  
User Exists (1.0ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."tenant_id" = $2 LIMIT $3  [["email", "aviisekh@gmail.com"], ["tenant_id", 115], ["LIMIT", 1]]
User Exists (0.7ms)  SELECT  1 AS one FROM "users" WHERE "users"."phone" = $1 AND "users"."tenant_id" = $2 LIMIT $3  [["phone", "+19843288951"], ["tenant_id", 115], ["LIMIT", 1]]
=> false
```

2. When devise is disabled in the model. 
```ruby
User.new(name: 'Test', email: 'aviisekh@gmail.com', tenant_id: 115, phone: "+19843288951").valid?
```

produces following two queries with result true
```sql
User Exists (1.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."tenant_id" = $2 LIMIT $3  [["email", "aviisekh@gmail.com"], ["tenant_id", 115], ["LIMIT", 1]]
User Exists (1.1ms)  SELECT  1 AS one FROM "users" WHERE "users"."phone" = $1 AND "users"."tenant_id" = $2 LIMIT $3  [["phone", "+19843288951"], ["tenant_id", 115], ["LIMIT", 1]]
=> true
```

I looks like it is buggy somewhere when we are using this gem with devise. Need to have its fix asap.

**Comment by aviisekh** [comment]
The above issue is fixed by removing the validatable module of devise in the model and writing the customer validation rules on email and password.

**Comment by excid3** [comment]
For Jumpstart Pro, we have the User model from Devise live outside the tenant. Users are associated with Tenants using a join record. You can use `accepts_nested_attributes_for :tenant` if you'd like to create a User and Tenant at the same time when they register.
