### ISSUE TITLE
test_tenant_middleware.rb not present after bundle install

### ISSUE THREAD

**Issue by rrojasv** [ErwinM/acts_as_tenant#215]
I am using RVM for handling the project's gem and after including this gem 'acts_as_tenant', '~> 0.4.4' on the gemFile.

require_dependency **'acts_as_tenant/test_tenant_middleware'** is crashing because that file is never found.

`require': No such file to load -- acts_as_tenant/test_tenant_middleware.rb (LoadError).

The error goes away if I add the file manually to the gem folder. Any ideas?

**Comment by niborg** [comment]
@rrojasv looks like the most recent version on master has not been deployed on rubygems. Try this in your gemfile:
```
gem 'acts_as_tenant',  git: 'https://github.com/ErwinM/acts_as_tenant', branch: 'master'
```

@ErwinM FYI

**Comment by martinGerez** [comment]
Issue was solved using github repo. Thanks.

**Comment by bchangg** [comment]
I am experiencing the same issue and have solved it with the above solution. However, I am wondering about future possibilities of the gem being incompatible with Rails versions or security patches and how this would be mitigated?

**Comment by benlangfeld** [comment]
@ErwinM Is it possible to cut a release?
