### ISSUE TITLE
Use of RequestStore - which makes use of Thread.current - the merits of this approach?

### ISSUE THREAD

**Issue by BKSpurgeon** [ErwinM/acts_as_tenant#217]
Hi friends

## Is RequestStore / Thread.current a good approach?

I noticed that acts_as_tenant makes extensive use of a library called request_store - [see here for example](https://github.com/ErwinM/acts_as_tenant/blob/master/lib/acts_as_tenant/model_extensions.rb). And the request store acts like a wrapper for `Thread.current` ([see here](https://github.com/steveklabnik/request_store/blob/master/lib/request_store.rb)) - in other words, global variables are being used (at least that's my understanding).

My question is: why are global variables being used in this manner? Would a better approach be to use a rack environment variable to set the current tenant throughout the course of a request, rather than implicitly relying on `Thread.current`? (There may be incorrect assumptions within my question).

Was wondering if any of you have thoughts on this?

chrs

**Comment by excid3** [comment]
The request store readme explains why to use it over Thread.current: https://github.com/steveklabnik/request_store
