### ISSUE TITLE
Setting config.require_tenant to be true except in application_controller.rb

### ISSUE THREAD

**Issue by veeral-patel** [ErwinM/acts_as_tenant#222]
Hi! I'd like to set config.require_tenant to be true so I don't accidentally forget to set the tenant and cause cross-tenant data leakage.

In my application_controller.rb, I'm reading a JWT from the Authorization header, checking if it's valid, getting the current user from it, and then setting the tenant based upon the current user.

If I have config.require_tenant to be on, though, I can't get the current user as no tenant has been set.

What I'd like to do is just set config.require_tenant to be false in application_controller.rb. But for every other file in my codebase, I'd like it to be true.

Any ideas on how to achieve this? @excid3

**Comment by excid3** [comment]
I'm not sure how require_tenant works internally, but you could just redirect if no tenant is found in your `before_action`. That should accomplish the same goal I think.

**Comment by veeral-patel** [comment]
@excid3 got it, so I think what you're saying is add a before_action callback after my authentication code (which is also a before_action) that ensures a tenant is set.

I think this would work. I think I'd prefer setting `config.require_tenant` so that if I don't set a tenant in my Rails console, then the program will complain as well, but I'm going to try your approach for now @excid3 

Thanks!

**Comment by excid3** [comment]
Actually, the code looks like `require_tenant` mostly just adds a default_scope to the model, so you could probably instead unscope your JWT and user lookup code so it skips that.

`User.unscoped.find` should work to remove the scope. And I'd leave a comment on that line to explain why you're doing unscoped there just to be safe.

**Comment by veeral-patel** [comment]
@excid3 I'll try that - thank you very much!!

**Comment by yshmarov** [comment]
@veeral-patel I found this method kind of useless

```
ActsAsTenant.configure do |config|
  config.require_tenant = false # true
end

```
Here's a solution for you:
```
  before_action :require_tenant
  def require_tenant
    if current_tenant.nil?
      redirect_to root_path, alert: "No tenant set!"
    end
  end

```
