### ISSUE TITLE
Relationship cache causes unexpected behaviour

### ISSUE THREAD

**Issue by bernardeli** [ErwinM/acts_as_tenant#226]
Hello there.

First of all, thanks for the work that have been put on this gem.

I'm currently introducing tenancy to an app and have encountered unexpected behaviour due to this override: 

https://github.com/ErwinM/acts_as_tenant/blob/1ba28d1354848fd422603efa343b145bae5c5fdf/lib/acts_as_tenant/model_extensions.rb#L181-L188

My understanding is that by returning the `ActsAsTenant.current_tenant`, the gains are negligible. Another downside of this approach is, if the tenant object changed between when it was first loaded to when the association is called, it causes to return a stale object.

By letting `belongs_to` work as intended, it hits the db, taking less than 0.5ms, and AR caches it for free after that.

I looked the commits history to understand the reason behind it but couldn't find anything.

Is there a real need for it? Would you consider removing it? I'd be happy to do the work.

I appreciate your help and time.

**Comment by excid3** [comment]
This should be fixed in master now. 👍
