### ISSUE TITLE
Scoping fails on new objects

### ISSUE THREAD

**Issue by borisd** [ErwinM/acts_as_tenant#227]
If accidently scoping is done on an object with invalid id (null or non numeric) - scoping is ignored

```
ActsAsTenant.current_tenant = Account.new / OpenStruct.new(id: nil)

Project.all =>  # all projects instead of empty result
```

**Comment by excid3** [comment]
Definitely think this is a bug. I want to make sure I'm thinking through all the cases here.

`has_global_records` uses `nil` to find all the tenant's records and records unassociated with a tenant. That's effectively what is going on here.

I'm thinking we want:

If `Account.id` is `nil` and `has_global_records: false` we should return `Project.where(account_id: [])`
If `Account.id` is `1` and `has_global_records: false` we should return `Project.where(account_id: [1])`
If `Account.id` is `nil` and `has_global_records: true` we should return `Project.where(account_id: [nil])`
If `Account.id` is `1` and `has_global_records: true` we should return `Project.where(account_id: [1, nil])`
