### ISSUE TITLE
Deprecation warning on autoloaded constants

### ISSUE THREAD

**Issue by dcoder2099** [ErwinM/acts_as_tenant#229]
I just added `acts_as_tenant` (0.4.4) to a relatively stable (and new) rails 6 project and began receiving the following warning when running rspec:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /Users/daniel/Development/miscellaneous/finsite-portal/config/environment.rb:5)
```

When I get some time, I will try to create a minimal test case for reproducing it, but in the meantime has anybody else experienced this?

Specifics: ruby 2.7.0; rails 6.0.2.2; rspec-rails ~> 4.0

**Comment by bojates** [comment]
I'm seeing the same thing on a fresh rails project with just rspec-rails and acts_as_tenant as additional gems. 
ruby 2.6.6; rails: 6.0.3; rspec-rails ~> 4.0
