### ISSUE TITLE
"set_current_tenant" method doesn't work

### ISSUE THREAD

**Issue by patdec** [ErwinM/acts_as_tenant#233]
Hi,

I use acts_as_tenant in a Ruby on Rails 6 application, and I can't set the current tenant in my base controller.

you can see it below:

```ruby
class BaseController < ApplicationController
    set_current_tenant_through_filter
    before_action :find_tenant
 
     private

    def find_tenant
      organization = Organization.find_by(url: request.host.sub(/\A\w+\./, '')
      set_current_tenant(organization)
    end
end
```

"set_current_tenant" method hasn't any effect. Tenant is never stored.

I tried to debug with **binding.pry**. In any method of my controllers ActsAsTenant.current_tenant returns nil.

I looked up  in the code what could be the reason and discovered the gem *request_store* is used to store the tenant.

I did some tests with this gem, and it looks it has some issues:

```ruby
RequestStore.store[:tenant] = 'mine' 
=> "mine"
>> RequestStore.store[:tenant]
=> nil
```

I posted an issue about this: https://github.com/steveklabnik/request_store/issues/70

Well. I can't use acts_as_tenant for now.

**Comment by patdec** [comment]
It works now. The issue was certainly related to my environment.

**Comment by schappim** [comment]
@patdec could you please provide more info, as I've found myself in the same position...
