### ISSUE TITLE
Help maintaining acts_as_tenant

### ISSUE THREAD

**Issue by excid3** [ErwinM/acts_as_tenant#234]
Hey @ErwinM! 👋 

Saw you were looking for maintainers and wanted to offer my help. I'm using ActsAsTenant heavily in https://jumpstartrails.com/ and we've got a few hundred apps using it. I guess that makes me an accidental expert and I really like using ActsAsTenant. 💪

I think we could get some of these issues knocked out and a new release cut pretty quickly. I'd like to also add some enhancements to make this work nicely with ActionCable since websockets will also need access to the current account.

Couldn't find your email so I thought opening an issue would be the next best place to contact you.

Thanks for all your work! Happy to help it live onwards.

**Comment by haffla** [comment]
@ErwinM? I am using this gem heavily, too, and hate to see it neglected. Anyway thanks for creating it. I'd be happy to help.

**Comment by niborg** [comment]
At this point, I think @excid3 you should just fork it.

**Comment by brandoncordell** [comment]
@excid3 I'd be happy to pitch in to help maintain a fork!

**Comment by excid3** [comment]
I'm fine maintaining a fork, but I'd rather support the original library since it's so popular and that would help the most people.

**Comment by niborg** [comment]
@excid3 I've been getting pinged about this problem for a VERY long time now. My suggestion:
- Make a fork.
- Comment in every outstanding PR and issue that there is now a fork that would welcome the person's contribution.

**Comment by excid3** [comment]
Here's my fork: https://github.com/excid3/acts_as_tenant

I opened up issues there. Anyone who wants to contribute is welcome and hopefully we can merge it into the main repo eventually. 🤞

**Comment by disastrous-charly** [comment]
So, is @excid3 fork is now the new official fork?

**Comment by brandoncordell** [comment]
@disastrous-charly Not technically an _official_ fork but @excid3 is well known and trusted in the community so it's a good fit until @ErwinM can pass the torch on this repo to someone else.

**Comment by excid3** [comment]
Just made a bunch of updates today. Now using Appraisal to run tests against Rails 5.2, 6.0, and master. Also refactored some things into concerns, and other general cleanup like using standardrb.

Thanks for the contributions everybody! 🎉

**Comment by bernardeli** [comment]
Thanks, @excid3.

I support this ownership change. This gem is an important part of @fivegoodfriends architecture. I am open to help, whenever I can, and see some love to keep things up to date and bugs free.

**Comment by ErwinM** [comment]
Hi all, I just added @excid3 as a collaborator to the repo.
