### ISSUE TITLE
model_extensions.rb: depreciation warning

### ISSUE THREAD

**Issue by yshmarov** [ErwinM/acts_as_tenant#235]
`/home/ubuntu/.rvm/gems/ruby-2.7.1/gems/acts_as_tenant-0.4.4/lib/acts_as_tenant/model_extensions.rb:111: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

**Comment by pond** [comment]
👍 on this - under 2.7.x, this deprecation warning happens quite often. While various [blog posts](https://piechowski.io/post/last-arg-keyword-deprecated-ruby-2-7/) suggest the usual simple `**` fix, this would force a gem to only work on Ruby 2.7.x, but [the _official_ docs](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) are fortunately way more accurate and helpful than the blog posts I've read so far and give options for < Ruby 2.7 support.

**Comment by haffla** [comment]
This has been fixed, but the change has not been released unfortunately.

**Comment by excid3** [comment]
Erwin granted me maintainer access to the gem, so once he adds me to Rubygems, I'll cut a new release. Hopefully tonight! 👍
