### ISSUE TITLE
Removing all Tenant Models

### ISSUE THREAD

**Issue by aximuseng** [ErwinM/acts_as_tenant#261]
Can you return all the models that are active in the Tenant?

I am looking to have active_admin 'wipe' a tenant and override all callbacks (had_many and ancestry restrictions) etc.

**Comment by aximuseng** [comment]
To clarify I mean like the functionality Searchkick has:

`Searchkick.models.each do |model|
          puts "Reindexing #{model.name} on #{tenant.tenant_name}"
          model.reindex
        end`

**Comment by excid3** [comment]
ActsAsTenant doesn't keep track of what models you have scoped anywhere.

**Comment by aximuseng** [comment]
Ok - was just hoping there was a quick method like Searchkick has.  I even looked in the source code for SK trying to figure out how that method works and apply that in AAT - no luck so far. 

I am guessing there is nothing past `Model.account.present?` to test each model and confirm it has a tenant.  Looking to ensure I don't orphan a ton of records each time I destroy a tenant.

**Comment by drj17** [comment]
@aximuseng did you figure out any convenient solution for this?  I ended up just adding a `has_many` reference for every tenant models with `dependent: :destroy`, but it's somewhat error prone.

**Comment by aximuseng** [comment]
I never got past this post and my efforts stalled.  That is probably a good starting point.  As you mentioned the potential for errors / disaster is there.  In my case I have some pretty complex relationships and while testing various solutions I ran into issues where unless I have the tenant models destroyed in a very specific order it throws foreign key errors etc.

It feels like that scene from Apollo 13 where ground back-up team is trying to engineer the perfect sequence in the simulator and power-up the spacecraft without overloading the battery 🤣🚀

**Comment by blombard** [comment]
I have the same problem. I would like to be able to delete all data linked to a tenant.

I wrote this funny script to solve this problem but I am not sure yet if I would trust it with production data? 😇 

```ruby
ActsAsTenant.current_tenant = Tenant.first

ActiveRecord::Base.transaction do
  data = true
  while data
    data = false
    ApplicationRecord.descendants.each do |model|
      next unless model.column_names.include?('tenant_id')

      begin
        ActiveRecord::Base.transaction(requires_new: true) do
          model.delete_all
        end
      rescue ActiveRecord::StatementInvalid
        data = true
      end
    end
  end

  ActsAsTenant.current_tenant.destroy!
end
```
