### ISSUE TITLE
 issue on devise compatibility

### ISSUE THREAD

**Issue by iprog21** [ErwinM/acts_as_tenant#276]
I am trying to register a new user with same email on different tenants. I saw this 
`validates_uniqueness_to_tenant :name, :email` on the documentation. but it seems not working. devise still validating the uniqueness of the email. is there any solution on this? or I need to do magic on it :) .

Rails Version: 7.0.2.2
Ruby Version: 3.1.0

**Comment by excid3** [comment]
You'll need to disable the Devise `validatable` module on your model.
