### ISSUE TITLE
Is there a way to disable in the console?

### ISSUE THREAD

**Issue by ConfusedVorlon** [ErwinM/acts_as_tenant#309]
I love this gem - so firstly, thank you for creating it.

I run things with `config.require_tenant = true` this is brilliant, and it stops me from accidentally shooting myself in the foot.

However - it is annoying when I'm debugging in the console. 

Is there a way for me to turn off require_tenant = true other than wrapping commands in a block?

e.g. `ActsAsDenant.beChillForThisSessionPlease()`

(syntax might vary!)

**Comment by blombard** [comment]
In `application.rb` you can do

```ruby
module YourApp
  class Application < Rails::Application
    # ...
    console do
      ActsAsTenant.require_tenant = false
      # or
      ActsAsTenant.current_tenant = Tenant.first
    end
  end
end
```
