### ISSUE TITLE
Enabling eager_loading causes NoTenantSet error

### ISSUE THREAD

**Issue by drale2k** [ErwinM/acts_as_tenant#318]
Hi, i am running into an issue with ActsAsTenant, which throws an `ActsAsTenant::Errors::NoTenantSet` error when booting the rails server, but only in production. The reason seems to be eager loading. It breaks on the following validation:

```ruby
validates :inbox_simcard_id, inclusion: { in: InboxSimcard.available.ids, message: "That Simcard is already taken" }
```

It seems to break when trying to access `InboxSimcard`. When i set `config.eager_loading = false` it works but i don't want to do that in production. 

I understand that it expects a tenant to be set during runtime, but on server boot? How am i supposed to set a tenant when the app is just booting?

**Comment by drale2k** [comment]
I was able to work around it refactoring my validation to not use a class and scope but an instance method instead, which performs the access via an association over the Account model. 

My guess is using an association fixed it since it can now go through the Account and therefore acts_as_tenant() is satisfied. 

I will leave this issue open because i would like to know if this is a bug with ActsAsTenant or is that just the way it is with ActsAsTenant and you can't call a scope on a call which has `acts_as_tenant` set.

I was banging my head for a day over this. For anyone else running into this issues, i went from:

```ruby
validates :inbox_simcard_id, inclusion: { in: InboxSimcard.available.ids, message: "That Simcard is already taken" }
```

to:

```ruby
validate :simcard_cannot_be_taken

def simcard_cannot_be_taken
  unless inbox_simcard_id.in?(account.inbox_simcards.available.ids)
    errors.add(:inbox_simcard_id, "That Simcard is already taken")
  end
end
```

**Comment by excid3** [comment]
Your original validation would have cached the ids on app boot, which is probably not what you wanted.
