### ISSUE TITLE
Question: Migration to CurrentAttributes.

### ISSUE THREAD

**Issue by barruda** [ErwinM/acts_as_tenant#325]
Hey there, first I would like to thanks for the amazing job, the gem is really a gem :drum:  :smile: 

May I kindly ask if the migration to ActiveSupport::CurrentAttributes have any relation to deprecation of rails 5.2?

I work on a big monolith on rails 5.2 and was planning to use it for authentication purposes...

Have you got any issues using it on 5.2 or is it only a conscidence?

Thanks VERY MUCH in advance !

**Comment by excid3** [comment]
CurrentAttributes was added in Rails 5.2 It should still work fine with 5.2, but we're no longer supporting it since it's EOL and our test suite requires Rails 6+.
