### ISSUE TITLE
Thread.Current storage under unicorn/thin

### ISSUE THREAD

**Issue by toxaq** [ErwinM/acts_as_tenant#34]
When using `thin` or `unicorn` Thread.Current isn't guaranteed to be cleared between requests, so you could end up having a tenant set when you don't want it set. [As per this SO Question](http://stackoverflow.com/questions/13829257/rails-how-to-handle-thread-current-data-under-a-single-threaded-server-like-thi)

There seems to be two solutions here:
1) Add a note to the readme to create a before_filter that sets the current_tenant to nil if you aren't explicitly setting a tenant for each request
2) Use something like [RequestStore](https://github.com/steveklabnik/request_store) as referenced in this [rails issue thread](https://github.com/rails/rails/issues/8517)

Thoughts?

**Comment by swordfish444** [comment]
@toxaq Were you ever able to determine the issue and what resolved it?

**Comment by toxaq** [comment]
@swordfish444 it's a long time ago now but I think Erwin's change to request_store resolved this but explicitly setting on every request in a before_filter also worked adequately.
