### ISSUE TITLE
Would you accept a PR adding support for a "through" option on belongs_to relationships?

### ISSUE THREAD

**Issue by tim-gq** [ErwinM/acts_as_tenant#345]
We have about 30 different instances similar to:

> Model Account
> 
> Model Project
> belongs_to :account
> 
> Model Task
> belongs_to :project

Where Task does not have an account_id on it, but we'd like to enforce acts_as_tenant via the `belongs_to :project` association.  We understand it comes with the caveat that loading a Task would necessitate loading the associated Project too.

I think it would likely involve:

* the default_scope :through handler will likely need adjusting - it kinda works as is.
* it should probably not try to create the belongs_to association.
* the validation handling would need adjustment to not try and validate the record itself.
* docs and tests to be added.

**Would you accept a PR that added support for it?**   Or are there some blockers I'm not seeing yet?

**Comment by excid3** [comment]
I can't remember exactly, but there's a `through` option it already handles: https://github.com/ErwinM/acts_as_tenant/blob/master/lib/acts_as_tenant/model_extensions.rb#L28

**Comment by tim-gq** [comment]
@excid3 Yes.  It doesn't correctly handle the use case I'm describing (an association via belongs_to).

I think our team is leaning towards adding account_id to the models directly though, so will probably not create this PR at this stage.

Thanks for the response @excid3.
