### ISSUE TITLE
Getting 'NoTenantSet' on some devise routes... :-/

### ISSUE THREAD

**Issue by joshuairl** [ErwinM/acts_as_tenant#49]
Any tips?

`ActsAsTenant::Errors::NoTenantSet`
Some of them include:
`/users/password/edit`
`/users/edit`

Any help is appreciated...

**Comment by fmh** [comment]
in application_controller.rb
  prepend_before_filter :your_method_to_get_current_tenant

**Comment by frenkel** [comment]
Override the sessions controller of devise by adding `controllers: { sessions: 'sessions' }` to your `devise_for` line in `config/routes.rb`

Now create the file `app/controllers/sessions_controller.rb` with contents like this

    class SessionsController < Devise::SessionsController
                                              
      set_current_tenant_through_filter
      prepend_before_action :set_tenant
                                           
      def set_tenant
        set_current_tenant(Tenant.find_by(subdomain: request.subdomain))
      end
    end

**Comment by ErwinM** [comment]
Thx @frenkel

**Comment by Arjeno** [comment]
A bit late maybe but this simple fix solves the issue for me:

```ruby
# lib/tenant_on_request.rb
require 'rack/request'

class TenantOnRequest

  def initialize(app, processor)
    @app = app
    @processor = processor
  end

  def call(env)
    request = Rack::Request.new(env)
    tenant = @processor.call(request)

    if tenant
      ActsAsTenant.with_tenant(tenant) { @app.call(env) }
    else
      @app.call(env)
    end
  end

end
```

Then in your application.rb add:
```ruby
    config.middleware.insert_before 'Warden::Manager',
                                    'TenantOnRequest',
                                    Proc.new { |request| Company.find_by(...) }

```

This makes sure the tenant (if any) is set before warden.

**Comment by johnunclesam** [comment]
@jfrux, @ErwinM this is happening to me just if I add `acts_as_tenant(:firm)` to my `user.rb` model.

But do you really need tenant on that model?

This is a nice question, I think.

Why tenant `account_id` on the `user` model? Maybe just for the administration logic?

And what if my administration logic is not in the same app?
