### ISSUE TITLE
no superclass method `organization'

### ISSUE THREAD

**Issue by dipth** [ErwinM/acts_as_tenant#74]
I have the following two models:

```ruby
class EmailTemplate < ActiveRecord::Base
  acts_as_tenant :organization
end

class Organization < ActiveRecord::Base
end
```

This worked when using ActsAsTenant version ```0.2.9``` but fails with the latest version ```0.3.4```

```ruby
EmailTemplate.first.organization
# We expect this to return an Organization instance, which it did before
```

Now it simply raises an error:

```
NoMethodError: super: no superclass method `organization' for #<EmailTemplate:0x007fde7d8cda58>
from /Users/thomas/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/activemodel-3.1.12/lib/active_model/attribute_methods.rb:385:in `method_missing'
```

We're using rails ```3.1.12``` and ruby ```1.9.3p194```

**Comment by ErwinM** [comment]
Sorry, this slipped past me. An answer so others might benefit:

This can be solved by putting an explicit 'belongs_to `:organization` in the `EmailTemplate` model. I'm not sure why that is required though...
