### ISSUE TITLE
ActsAsTenant::Errors::TenantIsImmutable

### ISSUE THREAD

**Issue by fmh** [ErwinM/acts_as_tenant#98]
Hi,
I have this error when i try edit a user.

**Comment by ErwinM** [comment]
This suggests you are trying to edit the tenant_id of the user. Which the gem will prevent..                                                                                                                                                                                                                                                                          Erwin                                                                                                                                                                                                                From: fmhSent: Saturday, 3 January 2015 04:00To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantSubject: [acts_as_tenant] ActsAsTenant::Errors::TenantIsImmutable (#98)Hi,
I have this error when i try edit a user.

—Reply to this email directly or view it on GitHub.

**Comment by fmh** [comment]
I only have a read only input in user form.
But modify user tenant is possible for admin for example !

**Comment by ErwinM** [comment]
Nope. You cannot edit the tenant column when using AaT. That was part of the design philosophy: strict separation of tenants so you don't have to worry about making a mistake and exposing the wrong information.

We use a separate admin app on the same db to do admin work.

**Comment by kirkonrails** [comment]
I understand the reason and disciplined approach to not allowing this to happen. But in some circumstances, it may be a little extreme.

This is what I've done for now.. it's ugly but it works until we have time to build an entire different admin system.

    # Used to bypass ActsAsTenant extreme approach to seperation.
    # This method should be used with extreme caution and only for admin accounts 
    def force_update_account_id(account_id)
      sql = "UPDATE courses SET account_id = #{account_id} WHERE id = #{self.id}"
      ActiveRecord::Base.connection.execute(sql)
    end

**Comment by bacrossland** [comment]
I agree with @kirkonrails on this. Not all projects I've worked on with tenants have a sperate admin application or want one. Especially the ones where the client is doing the administration. If someone messes up and creates an account in the wrong tenant they have to get a developer to change the record in the database or delete the account and start over. The end result is time sinks and user frustration. My thought is that it should be a configurable option to allow admins to change the tenant id.

**Comment by alxppp** [comment]
`:update_column` did the trick for me: `Model.find(x).update_column(:tenant_id, 123)`
